### ISSUE TITLE
A title for my issue

### ISSUE THREAD

**Issue by jules32** [Openscapes/2021-fdd#2]
Some beginning text

**Comment by jules32** [comment]
**Bold**

- [ ] this will be checklist


@AHolder1  can you this at this?

**Comment by AHolder1** [comment]
@jules32  - That's an awesome list! :)

**Comment by jules32** [comment]
Hey will you check out if we need these: https://github.com/amfriesz/lpdaac_hls_tutorial/blob/main/environment.yml#L10-L19

**Comment by AJONES8** [comment]
Looks good to me!
