### ISSUE TITLE
joke

### ISSUE THREAD

**Issue by kaycole** [Openscapes/2021-fdd#3]
@galuardi [why are tuna so smart?](https://www.foodhero.org/jokes/tuna-joke)

**Comment by galuardi** [comment]
**because they eat fish!**

**Comment by kaycole** [comment]
**hi** @lgcarlson

**Comment by AJONES8** [comment]
You can tune a piano but you can't tuna fish

**Comment by LGCarlson** [comment]
Finally figuring this out! 💯 
Did Walt tell you that tuna joke @galuardi?
