### ISSUE TITLE
Breakout Room Discussion

### ISSUE THREAD

**Issue by angeliamarie4** [Openscapes/2021-fdd#5]
@MaC-Perez @DonnaDim Are you all understanding how to navigate GitHub?

**Comment by MaC-Perez** [comment]
Hi Angelia

**Comment by MaC-Perez** [comment]
@angeliamarie4  XD

**Comment by angeliamarie4** [comment]
@MaxGrezlik take a look at this task list 

- [ ] meet for seaside chat 
- [ ] edit md file
