### ISSUE TITLE
Elephant image didn't show up

### ISSUE THREAD

**Issue by DonnaDim** [Openscapes/2021-fdd#9]
This line of code of quarto markdown didn't work for me: 

[![Caption](elephant.png)](https://quarto.org "An elephant")

@angeliamarie4

**Comment by MaC-Perez** [comment]
I could not add the image either

**Comment by jules32** [comment]
Hi @DonnaDim and @MaC-Perez, 

What you've written above ( `[![Caption](elephant.png)](https://quarto.org "An elephant")` ) is looking for a file called `elephant.png` here and it doesn't see one so it won't show up. I can upload an image by drag-and-drop; for me it's easiest to take a screenshot of that elephant that's copied to my clipboard and I'll paste here: 

<img width="74" alt="image" src="https://user-images.githubusercontent.com/5891909/134410699-9c8a66db-4753-46a8-a629-f20ea7501c6f.png">
